import conf from "nd/conf"
import { map } from "ramda"
import langs from "../lib/langs"

export default {
  lang: langs["en"],
  data_storage: "localforage",
  image_map: {},
  blog_articles: [],
  blog_data: null,
  articles: null,
  magazines: null,
  all_articles: null,
  private_articles: null,
  unlisted_articles: null,
  restricted_articles: null,
  private_magazines: null,
  unlisted_magazines: null,
  restricted_magazines: null,
  writer: null,
  next_articles: false,
  next_all_articles: false,
  next_private_articles: false,
  next_unlisted_articles: false,
  next_restrected_articles: false,
  next_magazines: false,
  next_private_magazines: false,
  next_unlisted_magazines: false,
  next_restrected_magazines: false,
  next_bloggers: false,
  bloggers: null,
  next_gallery: false,
  prevew_html: null,
  my_epics: null,
  epic_map: {},
  blog_todos: [],
  blog_todo_map: {},
  blog_map: {},
  personal_blog_todos: [],
  personal_blog_todo_map: {},
  personal_blog_epic: null,
  notifications: [],
  unread: [],
  next_notifications: false,
  next_unread: false,
  isNotifications: false,
  comment_selected: null,
  _comment_map: {},
  _article_map: {},
  article_map: {},
  covers: [],
  hit_users: [],
  hit_users2: [],
  comments: [],
  next_comments: false,
  blog_user_map: {},
  topics: [],
  posting_alis: false,
  posting_blog: false,
  posting_article: false,
  uploading_image: false,
  gallery: [],
  users: [],
}
