export default {
  ja: {
    key: "ja",
    notifications: "通知",
    comments: "コメント",
    name: "名前",
    delete: "削除",
    cancel: "キャンセル",
    change_settings: "設定変更",
    saving_userdata: "ユーザーデータを保存中...",
    lang: "言語",
    tag: "タグ",
    tags: "タグ一覧",
    hour: "時間",
    day: "日",
    minute: "分",
    dataID: "データID",
    last_update: "最終データ更新",
    saved: "保存しました",
    save_local: "ローカル保存日時",
    save_remove: "リモート保存日時",
    owner_id: "オーナーID",
    storage: "ストレージ",
    download: "ダウンロード",
    backup: "バックアップ",
    back: "戻る",
    unread: "未読",
    articles: "記事",
    enter_name: "名前を入力して下さい。",
    magazines: "マガジン",
    new_comments: "新着コメント",
    comment_articles: "コメント記事",
    replied_comment: "このコメントに対する返信です",
    read_more: "さらに読み込む...",
    load_more: "さらに読み込む...",
    manage_users: "ユーザー管理",
    language: "言語",
    remote_sync: "リモート同期",
    pull: "同期",
    data_corrupt: "データ形式が違います",
    login_with_did3: "DIDでログイン",
    link_did3: "DIDを接続",
    unlink_pre: "",
    unlink_post: "を切断",
    logout: "ログアウト",
    login: "ログイン",
    loading: "読み込み中...",
    username30: "ユーザー名（３０文字以内）",
    title100: "タイトル（１００文字以内）",
    enter_username: "ユーザー名を入力して下さい",
    create_user: "ユーザー作成",
    intro: "自己紹介",
    loading_article: "記事を読み込み中...",
    posting_article: "記事を投稿中...",
    icon: "アイコン",
    no_article: "記事が存在しません",
    loading_comments: "コメントを読み込み中...",
    copied: "コピーしました",
    preview: "プレビュー",
    toc: "目次",
    table_of_contents: "目次",
    edit_history: "編集履歴",
    article_title: "記事タイトル",
    reset: "リセット",
    save_history: "履歴保存",
    clear_history: "編集履歴を消去しエディタをクリアしてよろしいですか？",
    cover_image: "カバー画像",
    choose_cover:
      "カバー画像を選択して下さい。記事一覧表示やツイッター等でシェアされるときに使われます。",
    choose_topics: "トピックを３つまで選択して下さい。",
    up_to_3_topics: "選択可能なトピックは３つまでです。",
    unpublish: "下書きに戻す",
    allow_download: "第三者の記事マークダウンファイルのダウンロード",
    intro300: "概要（３００文字以内）",
    about: "概要",
    allow: "許可する",
    only_url: "記事URLからのみアクセス可能",
    unlisted: "公開リストに載せない",
    unlisted_in_list: "公開マガジンリストに掲載しません",
    offline_no_share:
      "※ オフラインの記事は第三者には見えないのでURLをシェアしないでください。",
    cannot_see_online: "※ オフラインモード中はオンラインの記事は見れません。",
    draft_not_public:
      "また下書き投稿の場合はまだ上記アドレスに公開されていません。",
    online: "オンライン",
    offline: "オフライン",
    import: "インポート",
    fetch: "データ取得",
    export: "エクスポート",
    no_offline_data: "オフラインデータはありません",
    edit: "編集",
    remove_coauthor: "自分を共同編集者から外してよろしいですか？",
    author_removed: "共同編集者から外れました",
    coauthoring: "共同編集",
    full_preview: "フルプレビュー",
    delete: "削除",
    deleted: "削除されました",
    reply: "返信",
    edited: "編集済",
    delete_confirmation: "削除してよろしいですか？",
    publish: "公開",
    published: "公開",
    post: "投稿",
    article_missing: "記事が存在しないか編集権限がありません。",
    article_url: "記事URL",
    no_photo: "記事内に画像がありません。",
    enter_title: "タイトルを入力してください",
    post_draft: "下書き保存",
    post_public: "公開投稿",
    start_typing: "本文を入力してください...",
    back_to_edit: "編集に戻る",
    post_settings: "投稿確認",
    post_tab: "投稿設定",
    manage_data: "データ管理",
    manage_accounts: "アカウント管理",
    admin: "アドミン",
    setting: "設定",
    all: "全て",
    none: "なし",
    save: "保存",
    unable_change: "変更不可",
    data_storage: "データ保存場所",
    blog: "自分の記事",
    mypage: "マイ公開ページ",
    magazines: "自分のマガジン",
    users: "ユーザー",
    _blog: "ブログ",
    _magazines: "マガジン",
    public_articles: "公開記事",
    draft_articles: "下書き",
    restricted_articles: "限定公開",
    unlisted_articles: "非掲載",
    private_magazines: "非公開",
    unsorted: "未分類",
    create_article: "記事作成",
    create_magazine: "マガジン作成",
    edit_article: "編集",
    others_pre: "他",
    others_post: "名",
    no_users: "ユーザーがいません",
    enter_comment: "コメントを入力してください...",
    comment1000: "コメントは1000文字以内で入力してください。",
    commenting: "コメントする",
    not_compatible:
      "Markdownとリッチテキストエディタの互換性が100%でないため、エディタを切り替えるといくつかのスタイルが失われる可能性がありますがよろしいですか？編集履歴機能で過去の状態に戻ることができます。",
    limit_access: "アクセス制限",
    access: "アクセス",
    get_all_users: "全ユーザー取得",
    cannot_remove_coauthor: "共同編集者は外せません。",
    coauthors4: "共同編集者（４人まで）",
    only_4authors: "共同編集者の選択は４人までです。",
    copy_url: "コピーURL",
    reorder: "並び替え",
    manage_article: "記事追加削除",
    manage_articles: "記事管理",
    no_magazine: "マガジンがありません",
    who_can_view: "限定公開者",
    cannot_remove_others: "他人の記事は外せません",
    delete_magazine: "マガジンを削除してもよろしいですか？",
    saving: "保存中...",
    gallery: "ギャラリー",
    advanced: "詳細設定",
    importMD: "インポートMD",
    download_all: "全データダウンロード",
    importJSON: "データインポート",
    wrong: "エラーが発生しました！",
    import_confirmation:
      "既存のオフラインデータを全て上書きしてよろしいですか？",
    _articles: "記事",
    images: "画像",
    backup_current_data: "利用中のデータをバックアップ",
    sign_and_pass: "クリプトウォレットで署名することでIPFSにアクセスできます",
    confirm_backup_remove: "バックアップデータを消去してよろしいですか？",
    wallet_connect: "ウォレット接続",
    disconnect: "切断",
    confirm_import:
      "ご利用中のオフラインデータを上書きしてインポートしてよろしいですか？",
  },
  en: {
    key: "en",
    notifications: "New!",
    comments: "Comments",
    name: "Name",
    delete: "Delete",
    deleted: "Deleted",
    reply: "Reply",
    edited: "Edited",
    cancel: "Cancel",
    change_settings: "Settings",
    saving_userdata: "Saving User Data...",
    lang: "Language",
    tag: "Tag",
    tags: "Tags",
    hour: "hrs",
    day: "days",
    minute: "mins",
    dataID: "Data ID",
    last_update: "Last Update",
    saved: "Saved",
    save_local: "Local Update",
    save_remote: "Remote Update",
    owner_id: "Owner ID",
    storage: "Storage",
    download: "Download",
    backup: "Backup",
    back: "Back",
    unread: "Unread",
    articles: "Articles",
    enter_name: "Enter Name",
    magazines: "Magazines",
    new_comments: "New Comments",
    comment_articles: "Comment Articles",
    replied_comment: "Replied Comment",
    read_more: "Read More...",
    load_more: "Load More...",
    manage_users: "Manage Users",
    language: "Language",
    remote_sync: "Pull Remote",
    pull: "Pull",
    data_corrupt: "Data seems to be corrupted...",
    login_with_did3: "Login with DID",
    link_did3: "Link DID",
    unlink_pre: "Unlink ",
    unlink_post: "",
    logout: "Logout",
    login: "Login",
    loading: "Loading...",
    username30: "Username under 30 characters",
    title100: "Title under 100 characters",
    enter_username: "Enter Username",
    create_user: "Craete User",
    intro: "About",
    loading_article: "Loading Article...",
    posting_article: "Posting Article...",
    icon: "Icon",
    no_article: "Article Not Found",
    loading_comments: "Loading Comments...",
    copied: "Copied!",
    preview: "Preview",
    toc: "ToC",
    table_of_contents: "Table of Contents",
    edit_history: "History",
    start_typing: "Start typing here...",
    article_title: "Title",
    reset: "Reset",
    save_history: "Save History",
    clear_history: "Would you like to clear the editor and its history?",
    cover_image: "Cover Image",
    choose_cover:
      "Choose a cover photo. It will be used when your article is shared on SNS such as Twitter.",
    choose_topics: "Select up to 3 topics.",
    up_to_3_topics: "You can select up to 3 topics.",
    unpublish: "Unpublish",
    allow_download: "Enable Markdown Download by Your Readers",
    intro300: "About under 300 characters",
    about: "About",
    allow: "Allow",
    only_url: "Only those with the URL can access",
    unlisted: "Unlisted",
    unlisted_in_list: "It won't be listed in public lists.",
    article_url: "Article URL",
    offline_no_share:
      "* Don't shre your offline article URL. It's not accessible by others.",
    edit: "Edit",
    remove_coauthor: "Would you like to remove yourself from the co-authors?",
    author_removed: "You have been removed from the co-authors!",
    coauthoring: "Co-Authoring",
    online: "Online",
    offline: "Offline",
    import: "Import",
    fetch: "Fetch",
    export: "Export",
    no_offline_data: "You have no offline data.",
    full_preview: "Full Preview",
    delete: "Delete",
    delete_confirmation: "Would you like to delete it?",
    post: "Post",
    publish: "Publish",
    published: "Published",
    article_missing:
      "The article doesn't exist or you don't have access to it.",
    cannot_see_online:
      "* You cannot view online articles while in offline mode.",
    draft_not_public: "Also, if your article is a draft, it's not public yet",
    enter_title: "Enter the Title",
    post_draft: "Save Draft",
    post_public: "Publish",
    no_photo: "There is no image in your article.",
    back_to_edit: "Back to Edit",
    post_settings: "to Posting",
    post_tab: "Post Settings",
    manage_data: "Manage Data",
    manage_accounts: "Manage Accounts",
    admin: "Admin",
    setting: "Settings",
    all: "All",
    biz: "Business",
    none: "None",
    repeat: "Repeat",
    save: "Save",
    data_storage: "Data Storage",
    blog: "Your Articles",
    mypage: "Your Public Page",
    magazines: "Your Magazines",
    users: "Users",
    _blog: "Blog",
    _magazines: "Magazines",
    public_articles: "Public",
    draft_articles: "Drafts",
    restricted_articles: "Restricted",
    unlisted_articles: "Unlisted",
    private_magazines: "Private",
    unsorted: "Unsorted",
    create_article: "New Article",
    create_magazine: "New Magazine",
    edit_article: "Edit",
    others_pre: "",
    others_post: " others",
    no_users: "Users Not Found",
    enter_comment: "Enter Comment...",
    comment1000: "Enter comment under 1000 characters",
    commenting: "Comment",
    not_compatible:
      "Markdown and the rich text editor are not 100% compatible. You could lose some data and styles by switching. You can always get back to the previous revisions via history. Would you like to switch to the rich text editor?",
    limit_access: "Limit Access",
    access: "Access",
    get_all_users: "Get All Users",
    cannot_remove_coauthor: "Co-authors cannot be removed.",
    coauthors4: "Co-Authors (up to 4 people)",
    only_4authors: "You can add up to 4 co-authors",
    copy_url: "Copy URL",
    reorder: "Reorder",
    manage_article: "Add/Remove Articles",
    manage_articles: "Articles",
    no_magazine: "Magazine Not Found",
    who_can_view: "Who Can View",
    cannot_remove_others: "You cannot remove other's",
    delete_magazine: "Would you like to delete the magazine?",
    saving: "Saving...",
    gallery: "Gallery",
    advanced: "Advanced",
    importMD: "Import MD",
    download_all: "Download All Data",
    importJSON: "Import Data",
    wrong: "Something went wrong!",
    import_confirmation:
      "Would you like to overwrite all current offline data?",
    _articles: "articles",
    images: "images",
    backup_current_data: "Backup Current Data in USE",
    sign_and_pass: "Sign with your crypto wallet to access IPFS",
    confirm_backup_remove: "Would you like to delete your backup data?",
    wallet_connect: "Connect Wallet",
    disconnect: "Disconnect",
    confirm_import:
      "The current offline data will be overwritten by this import. Would you like to proceed?",
  },
}
